### ISSUE TITLE
Image view for local images failing

### ISSUE THREAD

**Issue by jeffreycwitt** [ProjectMirador/mirador-desktop#4]
After manually installing the mirador build from the mirador master branch, I got the app working.
I successfully loaded local files. 

Clicking on the local file takes me to the gallery view, but then nothing seems to happen when I click on a thumbnail in the gallery view. 

I can't seem to view the local image in image view. 

I don't have this problem with non-local images.

**Comment by versae** [comment]
Is it failing for all local images or just tiff files?

**Comment by versae** [comment]
Another thing to consider is that only Mirador builds with the new `iiif-evented-canvas`, like in the `detail_images_and_image_choice` branch, will work. Once merged, there should be no problem.

**Comment by jeffreycwitt** [comment]
The local files are jpgs (but the same problem occurs with .png) I haven't tried tiffs yet. While they are loading as thumbnails, I get no response when clicking on them as part of an attempt to see them in image view. 

I tried adding the build from `detail_images_image_choice` branch. But with this build, I actually get no response when clicking on "open". So I can't get far enough to load local files and see if they will work in imageView.

**Comment by versae** [comment]
That is weird. I put together some [binaries](https://stanford.box.com/v/mirador-desktop), maybe you could try with these.

**Comment by jeffreycwitt** [comment]
Works great from the mac darwin .app package.
I must be doing something weird in the npm build process

**Comment by versae** [comment]
Great. I'll try to make it easier the building process.
